[metadata]
creation_date = "2023/06/13"
integration = ["okta"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/06/13"
promotion = true

[rule]
author = ["Elastic"]
description = """
Okta ThreatInsight is a feature that provides valuable debug data regarding authentication and authorization processes,
which is logged in the system. Within this data, there is a specific field called threat_suspected, which represents
Okta's internal evaluation of the authentication or authorization workflow. When this field is set to True, it suggests
the presence of potential credential access techniques, such as password-spraying, bruteforcing, replay attacks, and
other similar threats.
"""
from = "now-30m"
index = ["filebeat-*", "logs-okta*"]
interval = "9m"
language = "kuery"
license = "Elastic License v2"
name = "Okta ThreatInsight Threat Suspected Promotion"
note = """## Setup

## Triage and analysis

This is a promotion rule for Okta ThreatInsight suspected threat events, which are alertable events per the vendor.
Consult vendor documentation on interpreting specific events.
"""
references = [
    "https://help.okta.com/en-us/Content/Topics/Security/threat-insight/configure-threatinsight-system-log.htm",
    "https://www.elastic.co/security-labs/testing-okta-visibility-and-detection-dorothy",
]
risk_score = 73
rule_id = "56d66fa8-09fd-11ee-81d7-f661ea17fbcd"
rule_name_override = "okta.display_message"
severity = "high"
tags = [
    "Elastic",
    "Identity",
    "Okta",
    "Continuous Monitoring",
    "SecOps",
    "Identity and Access",
    "Credential Access",
]
timestamp_override = "event.ingested"
type = "query"

query = '''
event.dataset:okta.system and okta.debug_context.debug_data.threat_suspected: true
'''


[[rule.severity_mapping]]
field = "okta.debug_context.debug_data.risk_level"
operator = "equals"
severity = "low"
value = "LOW"

[[rule.severity_mapping]]
field = "okta.debug_context.debug_data.risk_level"
operator = "equals"
severity = "medium"
value = "MEDIUM"

[[rule.severity_mapping]]
field = "okta.debug_context.debug_data.risk_level"
operator = "equals"
severity = "high"
value = "HIGH"

[[rule.threat]]
framework = "MITRE ATT&CK"

[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

