[metadata]
creation_date = "2023/04/03"
integration = ["windows", "endpoint"]
maturity = "production"
min_stack_comments = "The New Term rule type used in this rule was added in Elastic 8.4"
min_stack_version = "8.4.0"
updated_date = "2023/05/31"

[rule]
author = ["Elastic"]
description = """
Adversaries may install legitimate remote access tools (RAT) to compromised endpoints for further command-and-control
(C2). Adversaries can rely on installed RATs for persistence, execution of native commands and more. This rule detects
when a process is started whose name or code signature resembles commonly abused RATs. This is a New Terms rule type
indicating the host has not seen this RAT process started before within the last 30 days.
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*", "logs-windows.*"]
language = "kuery"
license = "Elastic License v2"
name = "First Time Seen Commonly Abused Remote Access Tool Execution"
references = [
    "https://thedfirreport.com/2023/04/03/malicious-iso-file-leads-to-domain-wide-ransomware/",
    "https://attack.mitre.org/techniques/T1219/",
]
risk_score = 47
rule_id = "6e1a2cc4-d260-11ed-8829-f661ea17fbcc"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Command and Control"]
timestamp_override = "event.ingested"
type = "new_terms"

query = '''
host.os.type:windows and event.category:process and event.type:start and (process.code_signature.subject_name:("Ammyy LLC" or "BeamYourScreen GmbH" or GlavSoft or "LogMeIn, Inc." or "Nanosystems S.r.l." or "NetSupport Ltd" or "Pro Softnet Corporation" or RealVNC or "Remote Utilities LLC" or SAFIB or ShowMyPC or "Splashtop Inc." or "Yakhnovets Denis Aleksandrovich IP" or uvnc or TeamViewer*) or process.name.caseless:(AeroAdmin.exe or AnyDesk.exe or AteraAgent.exe or B4-Service.exe or DWRCC.exe or ISLLight.exe or ISLLightClient.exe or LMIIgnition.exe or LogMeIn.exe or Mikogo-Service.exe or ROMServer.exe or ROMServer.exe or ROMViewer.exe or RPCSuite.exe or RemoteDesktopManager.exe or RemotePC.exe or RemotePCDesktop.exe or RemotePCService.exe or SRService.exe or Splashtop-streamer.exe or SupremoHelper.exe or apc_Admin.exe or apc_host.exe or r_server.exe or radmin.exe or rfusclient.exe or rutserv.exe or rutview.exe or smpcview.exe or spclink.exe or strwinclt.exe or teamviewer.exe or tvn.exe or tvnserver.exe or tvnviewer.exe or vncserver.exe or vncviewer.exe or winvnc.exe or AA_v*.exe, or ScreenConnect*.exe)) and not (process.pe.original_file_name:(G2M.exe or Updater.exe or powershell.exe) and process.code_signature.subject_name:"LogMeIn, Inc.")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1219"
name = "Remote Access Software"
reference = "https://attack.mitre.org/techniques/T1219/"


[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[rule.new_terms]
field = "new_terms_fields"
value = ["host.id"]
[[rule.new_terms.history_window_start]]
field = "history_window_start"
value = "now-15d"


