[metadata]
creation_date = "2023/05/25"
integration = ["auditd_manager"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/05/25"

[rule]
author = ["Elastic"]
description = """
An RDP (Remote Desktop Protocol) brute force attack involves an attacker repeatedly attempting various username and 
password combinations to gain unauthorized access to a remote computer via RDP, and if successful, the potential impact
can include unauthorized control over the compromised system, data theft, or the ability to launch further attacks 
within the network, jeopardizing the security and confidentiality of the targeted system and potentially compromising 
the entire network infrastructure. This rule identifies multiple consecutive authentication failures targeting a 
specific user account within a short time interval, followed by a succesful authentication.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-auditd_manager.auditd-*"]
language = "eql"
license = "Elastic License v2"
name = "Potential Succesful Linux RDP Brute Force Attack Detected"
note = """## Setup
This rule requires the use of the `auditd_manager` integration. 
"""

risk_score = 73
rule_id = "521fbe5c-a78d-4b6b-a323-f978b0e4c4c0"
severity = "high"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Credential Access"]
type = "eql"
query = '''
sequence by host.id, related.user with maxspan=5s
  [authentication where host.os.type == "linux" and event.action == "authenticated" and 
   auditd.data.terminal : "*rdp*" and event.outcome == "failure"] with runs=10

  [authentication where host.os.type == "linux" and event.action  == "authenticated" and 
   auditd.data.terminal : "*rdp*" and event.outcome == "success"] | tail 1
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1110"
name = "Brute Force"
reference = "https://attack.mitre.org/techniques/T1110/"
[[rule.threat.technique.subtechnique]]
id = "T1110.001"
name = "Password Guessing"
reference = "https://attack.mitre.org/techniques/T1110/001/"

[[rule.threat.technique.subtechnique]]
id = "T1110.003"
name = "Password Spraying"
reference = "https://attack.mitre.org/techniques/T1110/003/"



[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

